/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CustodyManager } from "./CustodyManager";
export type { HealthRegistry } from "./HealthRegistry";
export type { PetNFT } from "./PetNFT";
